package mocks

import (
	"github.com/marcelocquadros/blog/internal/app/domain/user" // adjust import path as per your project structure
	"github.com/stretchr/testify/mock"
)

// MockUserRepository is an autogenerated mock type for the UserRepository interface
type MockUserRepository struct {
	mock.Mock
}

// CreateUser provides a mock function with given fields: u
func (m *MockUserRepository) CreateUser(u *user.User) error {
	ret := m.Called(u)
	return ret.Error(0)
}

// DeleteUser provides a mock function with given fields: ID
func (m *MockUserRepository) DeleteUser(ID string) error {
	ret := m.Called(ID)
	return ret.Error(0)
}

// UpdateUser provides a mock function with given fields: u
func (m *MockUserRepository) UpdateUser(u *user.User) error {
	ret := m.Called(u)
	return ret.Error(0)
}

// FindAllUsers provides a mock function with given fields:
func (m *MockUserRepository) FindAllUsers() ([]user.User, error) {
	ret := m.Called()
	var r0 []user.User
	if ret.Get(0) != nil {
		r0 = ret.Get(0).([]user.User)
	}
	return r0, ret.Error(1)
}

// FindUserByID provides a mock function with given fields: ID
func (m *MockUserRepository) FindUserByID(ID string) (*user.User, error) {
	ret := m.Called(ID)
	var r0 *user.User
	if ret.Get(0) != nil {
		r0 = ret.Get(0).(*user.User)
	}
	return r0, ret.Error(1)
}
